courses/urls.py
# imports
from django.urls import path
from django.views.i18n import JavaScriptCatalog
from courses import views
# End: imports -----------------------------------------------------------------

app_name = 'courses'

urlpatterns = [
    # path(route, view, kwargs=None, name=None)
    path('all/', views.AllCoursesView.as_view(), name="all_courses"),
    path('add/', views.AddCourseView.as_view(), name="add_course"),
    path('<int:courseID>/', views.CourseView.as_view(), name="course_view"),
    path('delete/<int:courseID>/', views.DeleteCourseView.as_view(), name="delete_course"),
    path('edit/<int:courseID>/', views.EditCourseView.as_view(), name="edit_course"),
    path('duplicate/<int:courseID>/', views.DuplicateCourse.as_view(), name="duplicate_course"),
    path('export/<int:courseID>/', views.ExportView.as_view(), name="export_course"),
    path('spotify/create_playlist/<int:courseID>/', views.CreatePlaylistView.as_view(), name="create_playlist"),
]

events/urls.py
# imports
from django.urls import path

from events import views
# End: imports -----------------------------------------------------------------

app_name = 'events'

urlpatterns = [
    # path(route, view, kwargs=None, name=None)
    path('all/', views.AllEventsView.as_view(), name="all_events"),
    path('add/', views.AddEventView.as_view(), name="add_event"),
    path('<int:eventID>/', views.EventView.as_view(), name="event_view"),
    path('edit/<int:modelID>/', views.EditEventView.as_view(), name="edit_event"),
    path('signup/<int:modelID>/', views.EventSignup.as_view(), name="event_signup"),
]

info/urls.py
# imports
from django.urls import path
from info import views
from django.views.i18n import JavaScriptCatalog
# End: imports -----------------------------------------------------------------

app_name = 'info'

urlpatterns = [
    path('external/', views.external, name="external"),
    path('english/', views.english, name="english"),
    path('contact/', views.contact, name="contact"),
    path('about/', views.about, name="about"),
    path('hall_times/', views.hall_times, name="hall_times"),
    path('faq/', views.faq, name="faq"),
]

music_library/urls.py
from songs import views
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.views.i18n import JavaScriptCatalog


app_name = 'root'


urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', views.HomeView.as_view(), name="home"),
    path('forbidden/', views.ForbiddenView.as_view(), name="forbidden"),

    path('songs/', include('songs.urls')),
    path('account/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('courses/', include('courses.urls')),
    path('videos/', include('videos.urls')),
    path('info/', include('info.urls')),
    path('wiki/', include('wiki.urls')),
    path('events/', include('events.urls')),

    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('tinymce/', include('tinymce.urls')),
    path('select2/', include('django_select2.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

songs/urls.py
# imports
from django.urls import path
from django.views.i18n import JavaScriptCatalog
from songs import views
# End: imports -----------------------------------------------------------------

app_name = 'songs'

urlpatterns = [
    path('all/', views.AllSongsView.as_view(), name="all_songs"),
    path('add/', views.AddSongView.as_view(), name="add_song"),
    path('edit/<int:songID>', views.EditSongView.as_view(), name="edit_song"),
    path('delete/<int:songID>', views.DeleteSongView.as_view(), name="delete_song"),
    path('bpm_calc/', views.BPMView.as_view(), name="bpm_calc"),

    path('tags/add', views.AddTag.as_view(), name="add_tag"),
    path('tags/edit/<int:tagID>', views.EditTag.as_view(), name="edit_tag"),
    path('tags/all', views.AllTags.as_view(), name="all_tags"),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

videos/urls.py
# imports
from django.urls import path
from django.views.i18n import JavaScriptCatalog
from videos import views
# End: imports -----------------------------------------------------------------

app_name = 'videos'

urlpatterns = [
    path('add/', views.AddVideo.as_view(), name="add_video"),
    path('all/', views.AllVideos.as_view(), name="all_videos"),
    path('<int:videoID>', views.VideoView.as_view(), name="video_view"),
    path('edit/<int:videoID>', views.EditVideo.as_view(), name="edit_video"),
    path('delete/<int:videoID>', views.DeleteVideo.as_view(), name="delete_video"),
]

wiki/urls.py
# imports
from django.urls import path
from django.views.i18n import JavaScriptCatalog
from django.views.generic.detail import DetailView

from wiki import views
from wiki import models as wiki_models
# End: imports -----------------------------------------------------------------

app_name = 'wiki'


urlpatterns = [
    path('dashboard/', views.Dashboard.as_view(), name="dashboard"),

    path('folder/add/', views.AddFolder.as_view(), name="add_folder"),
    path('folder/edit/<int:modelID>/', views.EditFolder.as_view(), name="edit_folder"),

    path('page/add/', views.AddPage.as_view(), name="add_page"),
    path('page/edit/<int:modelID>/', views.EditPage.as_view(), name="edit_page"),
    path('page/<int:modelID>/', views.PageView.as_view(), name="page_view"), # Order is important
]

songs/models.py
# imports
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth import get_user_model

User = get_user_model()

# End: imports -----------------------------------------------------------------

class Tag(models.Model):
    title = models.CharField(null=True, blank=False, max_length=100, unique=True, verbose_name="Tittel")
    context = models.CharField(null=True, blank=True, max_length=100, help_text="Mellomrom-separerte nøkkelord for å relatere tag til kategori (Blank for ikke spesifikk type). Bruk: song, course eller video.")

    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, editable=False, verbose_name="Opprettet av")
    created = models.DateTimeField(null=True, blank=True, editable=False, verbose_name="Opprettet")

    def __str__(self):
        return self.title

    def context_list(self):
        if self.context: return self.context.split(" ")
        else: return []

    def getQueryset(context_list=None):
        a = Tag.objects.all()
        if not context_list:
            return a

        q = a.filter(context=None)
        for c in context_list:
            q = q | a.filter(context__icontains=c)
        return q

    def save(self, *args, **kwargs):
        if not self.id:
            self.created = timezone.now()
        return super(type(self), self).save(*args, **kwargs)


class Song(models.Model):
    title = models.CharField(max_length=150, null=True, blank=False, verbose_name="Tittel")
    artist = models.CharField(max_length=150, null=True, blank=False)
    bpm = models.SmallIntegerField(blank=True, null=True, help_text="Helst antall partall per minutt")
    spotify_URL = models.URLField(null=True, blank=False, help_text="Høyre klikk på sang -> Share -> Copy Song Link")
    spotify_URI = models.CharField(max_length=300, null=True, blank=False, help_text="Høyre klikk på sang -> Share -> Copy Spotify URI")
    tags = models.ManyToManyField('songs.Tag', blank=True)

    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, editable=False, verbose_name="Opprettet av")
    created = models.DateTimeField(null=True, blank=True, editable=False, verbose_name="Opprettet")

    class Meta:
        ordering = ['bpm', 'title']
        verbose_name = "Sang"
        verbose_name_plural = "Sanger"

    def __str__(self):
        return "{} - {} ({} bpm)".format(self.title, self.artist, self.bpm)

    def save(self, *args, **kwargs):
        if not self.id:
            self.created = timezone.now()
        return super(type(self), self).save(*args, **kwargs)

class File(models.Model):
    description = models.CharField(max_length=255, blank=True)
    file = models.FileField(upload_to='mediaroot/')

    def __str__(self):
        return "File {}".format(self.id)

songs/views.py
# imports
from __future__ import print_function
import json

from django.views import View
from django.db.models import Q
from django.conf import settings
from django.contrib import messages
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from django.contrib.auth import get_user_model

from songs import forms as song_forms
from songs import models as song_models

User = get_user_model()

# End: imports -----------------------------------------------------------------

# Functions

def update_songs_txt(song, title=None):
    tags = song.tags.values_list('navn')
    tags = [t[0] for t in tags]
    song = song.__dict__
    song = {'title': song['title'], 'artist': song['artist'], 'bpm': song['bpm'], 'tags': tags, 'spotify': song['spotify'], 'URI': song['URI'] }
    # Add:
    if title==None:
        with open('songs/static/songs/songs.txt', mode='a', encoding="UTF-8") as songs:
            songs.write(json.dumps(song, ensure_ascii=False) + "\n")
    # Update line:
    else:
        with open('songs/static/songs/songs.txt', mode='r', encoding="UTF-8") as songs:
            data = songs.readlines()

        for i in range(len(data)):
            if title in data[i]:
                data[i] = json.dumps(song, ensure_ascii=False) + "\n"

        with open('songs/static/songs/songs.txt', mode='w', encoding="UTF-8") as songs:
            songs.write("".join(data) + '\n')

# End: Functions ---------------------------------------------------------------


class HomeView(View):
    template = 'songs/home.html'

    def get(self, request):
        return render(request, self.template)


addSong_dec = [
    login_required,
]
@method_decorator(addSong_dec, name='dispatch')
class AddSongView(View):
    template = 'songs/song_form.html'
    form_class = song_forms.SongForm

    def get(self, request):
        form = self.form_class()
        return render(request, self.template, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            song = form.save()
            #update_songs_txt(song)
            messages.success(request, 'Du har klart å legge til en ny sang, så flink! :3')
            return redirect('songs:all_songs')
        else:
            return render(request, self.template, {'form': form})



editSong_dec = [
    login_required,
    permission_required('songs.change_song', login_url='forbidden')
]
@method_decorator(editSong_dec, name='dispatch')
class EditSongView(View):
    template = 'songs/song_form.html'
    form_class = song_forms.SongForm

    def get(self, request, songID):
        song = song_models.Song.objects.get(id=songID)
        form = self.form_class(instance=song)
        return render(request, self.template, {'form': form})

    def post(self, request, songID):
        song = song_models.Song.objects.get(id=songID)
        form = self.form_class(request.POST, instance=song)
        if form.is_valid():
            song = form.save()
            #update_songs_txt(song)
            return redirect('songs:all_songs')
        return render(request, self.template, {'form': form, 'songID': songID})


allSongs_dec = [
    login_required,
]
@method_decorator(allSongs_dec, name='dispatch')
class AllSongsView(View):
    template = 'songs/all_songs.html'
    form_class = song_forms.SongSearchForm

    def get(self, request):
        form = self.form_class()
        songs = song_models.Song.objects.all()
        return render(request, self.template, {'form': form, 'songs': songs.order_by('bpm')})

    def post(self, request):
        form = self.form_class(data=request.POST)
        songs = song_models.Song.objects.all()
        if form.is_valid():
            songs = self.search_song_filter(form=form, queryset=songs)
        return render(request, self.template, {'form': form, 'songs': songs.order_by('bpm')})


    def search_song_filter(self, form, queryset):
        search = form.cleaned_data['search']
        tag = form.cleaned_data['tag']
        check_min = form.cleaned_data['check_min']
        min_bpm = form.cleaned_data['min_bpm']
        check_max = form.cleaned_data['check_max']
        max_bpm = form.cleaned_data['max_bpm']

        if search != "":
            queryset = queryset.filter( Q(title__icontains=search) | Q(artist__icontains=search) )
        if tag != '-1':
            queryset = queryset.filter(tags__id=tag)
        if check_min and min_bpm != None:
            queryset = queryset.filter(bpm__gte=min_bpm)
        if check_max and max_bpm != None:
            queryset = queryset.filter(bpm__lte=max_bpm)

        return queryset


deleteSong_dec = [
    login_required,
    permission_required('songs.delete_song', login_url='forbidden'),
]
@method_decorator(deleteSong_dec, name='dispatch')
class DeleteSongView(View):

    def post(self, request, songID):
        song_models.Song.objects.get(id=songID).delete()
        messages.success(request, "Du har vellykket slettet en sang... Why tho? :'(")
        return redirect("songs:all_songs")



class BPMView(View):
    # https://github.com/selwin/django-user_agents
    template = 'songs/bpm_calc.html'

    def get(self, request):
        return render(request, self.template)

class ForbiddenView(View):
    template = 'songs/forbidden.html'

    def get(self, request):
        return render(request, self.template)


class AddTag(View):
    template = 'songs/tag_form.html'
    form_class = song_forms.TagForm

    def get(self, request):
        form = self.form_class()
        return render(request, self.template, {'form': form})

    def post(self, request):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('songs:all_tags')
        return render(request, self.template, {'form': form})

class EditTag(View):
    template = 'songs/tag_form.html'
    form_class = song_forms.TagForm

    def get(self, request, tagID):
        tag = song_models.Tag.objects.get(id=tagID)
        form = self.form_class(instance=tag)
        return render(request, self.template, {'form': form})

    def post(self, request, tagID):
        tag = song_models.Tag.objects.get(id=tagID)
        form = self.form_class(request.POST, instance=tag)

        if form.is_valid():
            form.save()
            return redirect('songs:all_tags')
        return render(request, self.template, {'form': form})

class AllTags(View):
    template = 'songs/all_tags.html'

    def get(self, request):
        tags = song_models.Tag.objects.all()
        return render(request, self.template, {'tags': tags})

songs/templates/songs/all_tags.html
{% extends 'songs/base.html' %}
{% load static %}

{% block title %}Alle tags{% endblock %}

{% block head %}

    <link rel="stylesheet" href="{% static "songs/css/song_styles.css" %}">

    <style>
        #btn-add-tag {
            position: sticky;
            top: 3.7em;
            z-index: 5;
        }

        {{ request.user.settings.song_theme.as_css }}
    </style>
{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'songs:all_tags' %}">Alle tags</a></li>
{% endblock %}

{% block body %}
    <div class="default-theme user-theme">

        <h1>Alle Tags:</h1>

        {% if perms.songs.add_tag %}
            <span id="btn-add-tag" class="">
                <a  class="btn btn-secondary" href="{% url 'songs:add_tag' %}">
                    <img src="https://img.icons8.com/material-rounded/25/000000/plus-math.png">
                    Legg til tag
                </a>
            </span>
        {% endif %}

        <div class="">
            {% for tag in tags %}
                <span class="">
                    <a href="{% url 'songs:edit_tag' tag.id %}">{{ tag.title }}</a>
                    {% for context in tag.context_list %}
                        <span class="badge badge-pill badge-secondary">{{ context }}</span>
                    {% endfor %}

                </span>
                <br>
            {% endfor %}
        </div>

    </div>
{% endblock %}

songs/templates/songs/footer.html
<!-- Footer -->
<footer id="footer" class="footer">
    <!-- Footer Links -->
    <div class="container text-center text-md-center">
        <!-- Grid row -->
        <div class="row">

            <!-- Grid column -->
            <div class="col-md-3 mx-auto">
                <!-- Links -->
                <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Musikk</h5>

                <ul class="list-unstyled">
                    <li><a href="{% url 'songs:all_songs' %}">Alle sanger</a></li>
                    {% if perms.songs.add_song %}
                        <li><a href="{% url 'songs:add_song' %}">Legg til sang</a></li>
                    {% endif %}
                    <li><a href="{% url 'songs:bpm_calc' %}">BPM Kalkulator</a></li>
                </ul>

            </div>


            {% if perms.courses.view_course %}
                <hr class="clearfix w-100 d-md-none">
                <!-- Grid column -->
                <div class="col-md-3 mx-auto">
                    <!-- Links -->
                    <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Kurs</h5>

                    <ul class="list-unstyled">
                        <li><a href="{% url 'courses:all_courses' %}">Alle kurs</a></li>
                        <li><a href="{% url 'courses:add_course' %}">Legg til kurs</a></li>
                    </ul>
                </div>
                <!-- End: Grid column 4 -->
            {% endif %}

            {% if perms.songs.view_tag %}
                <hr class="clearfix w-100 d-md-none">

                <!-- Grid column -->
                <div class="col-md-3 mx-auto">

                    <!-- Links -->
                    <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Tags</h5>

                    <ul class="list-unstyled">
                        <li><a href="{% url 'songs:all_tags' %}">Alle tags</a></li>
                        <li><a href="{% url 'songs:add_tag' %}">Legg til tag</a></li>
                    </ul>
                </div>
                <!-- End: Grid column 4 -->
            {% endif %}


            <hr class="clearfix w-100 d-md-none">

        </div>
        <!-- End: Grid row -->

    </div>
    <!-- End: Footer Links -->

    <div class="container">
        <!-- Social buttons -->
        <ul class="list-unstyled list-inline text-center">
            <li class="list-inline-item">
                <a target="_blank" href="https://www.facebook.com/NTNUISwingFolkedans/">
                    <img src="https://img.icons8.com/ios-glyphs/60/0065ff/facebook-circled.png">
                </a>
            </li>
            <li class="list-inline-item">
                <a target="_blank" href="https://www.instagram.com/ntnuiswingogfolkedans/">
                    <img src="https://img.icons8.com/ios/48/e542f4/instagram-new.png">
                </a>
            </li>
            <li class="list-inline-item">
                <a target="_blank" href="https://www.linkedin.com/company/ntnui-swing-og-folkedans/">
                    <img src="https://img.icons8.com/ios-glyphs/60/00AAFF/linkedin.png">
                </a>
            </li>
        </ul>
        <!-- Social buttons -->
    </div>

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3"> © {% now 'Y' %} Copyright:
        <a href="#"> Emil Telstad</a>
    </div>
    <!-- Copyright -->

</footer>
<!-- End: Footer -->

songs/templates/songs/navbar.html
<!-- Navbar -->
{% load static %}
<nav style="padding: 0px 0px 0px 20px" class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">

    <a style="padding: 0px; margin: 0px 30px 0px 0px" class="navbar-brand" href="{% url 'home' %}">
        <img style="filter: invert(1)" width="150" src="{% static "songs/images/swing-logo.png" %}" alt="">
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>


    <div id="navbar" class="collapse navbar-collapse mr-auto">
        <ul class="navbar-nav mr-auto">

            <!--
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Menu
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'info:external' %}">Eksterne kurs</a>
                    <a class="dropdown-item" href="{% url 'info:english' %}">Information in English</a>
                    <a class="dropdown-item" href="{% url 'info:contact' %}">Kontakt oss</a>
                    <a class="dropdown-item" href="{% url 'info:about' %}">Om oss</a>
                    <a class="dropdown-item" href="{% url 'info:hall_times' %}">Treningstider</a>
                    <a class="dropdown-item" href="{% url 'info:faq' %}">FAQ</a>
                </div>
            </li>
            -->

            <li class="nav-item">
                <a class="nav-link" href="{% url 'events:all_events' %}">
                    {# <img src="https://img.icons8.com/ios/24/FFFFFF/69.png"> #}
                    {# <i class="lni-timer"></i> #}
                    <i class="lni-calendar"></i>
                    Events
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'wiki:dashboard' %}">
                    {# <img src="https://img.icons8.com/ios/24/FFFFFF/69.png"> #}
                    <i class="lni-library"></i>
                    Wiki
                </a>
            </li>

            {% if perms.songs.view_songs %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'songs:all_songs' %}">
                        {# <img src="https://img.icons8.com/ios/24/FFFFFF/music.png"> #}
                        <i class="lni-spotify-original"></i>
                        Musikk
                    </a>
                </li>
            {% endif %}

            {% if perms.video.view_video %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'videos:all_videos' %}">
                        <i class="lni-youtube"></i>
                        Turbibliotek
                    </a>
                </li>
            {% endif %}

            {% if perms.course.view_course %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'courses:all_courses' %}">
                        {# <img src="https://img.icons8.com/wired/24/FFFFFF/planner.png"> #}
                        <i class="lni-control-panel"></i>
                        Kurs
                    </a>
                </li>
            {% endif %}

            {% if request.user.is_staff %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">
                        {# <img src="https://img.icons8.com/ios-filled/24/FFFFFF/microsoft-admin.png"> #}
                        <i class="lni-protection"></i>
                        Admin
                    </a>
                </li>
            {% endif %}

        </ul>
        {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a id="navbar-user" class="nav-link text-light" href="{% url 'accounts:profile' %}">
                        {# <img src="https://img.icons8.com/ios-glyphs/24/009900/user--v1.png"> #}
                        <i class="lni-user"></i>
                        {{ user.email }}
                    </a>
                </li>
            </ul>
        {% else %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Logg inn</a>
                </li>
            </ul>
        {% endif %}


    </div>
</nav> <!-- End: navbar -->

songs/templates/songs/song_form.html
{% extends 'songs/base.html' %}
{% block title %}Sang{% endblock %}

{% load static %}

{% block head %}
    <script type="text/javascript" src="{% url 'songs:javascript-catalog' %}"></script>

    {{ form.media }}

    <link rel="stylesheet" href="{% static "songs/css/song_styles.css" %}">

    <style media="screen">
        .selector select::-webkit-scrollbar {
            width: 0.4em;
        }
        .selector select::-webkit-scrollbar-thumb {
            background-color: rgba(0,0,0,1);
            border-radius: 10px;
        }
        .selector select::-webkit-scrollbar-track {
            background-color: white;
            border-radius: 10px;
        }
        .selector-available, .selector-chosen {
            width: 200px;
        }
        .selector h2 {
            font-size: 1.1em;
            color: white !important;
            background: rgba(255, 255, 255, 0.4) !important;
        }
        .selector select {
            width: inherit;
            height: 3.8em !important;
            color: white;
            background: rgba(255, 255, 255, 0.4);
        }
        .selector ul.selector-chooser {
            margin: 2.5em 5px 0 5px;
        }
        .selector .selector-filter, .selector .help-icon {
            display: none;
        }

        .tooltip-inner {
            background: green;
        }

        {{ request.user.settings.song_theme.as_css }}

    </style>
{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'songs:all_songs' %}">Alle sanger</a></li>
    {% if songID %}
        <li class="breadcrumb-item"><a href="{% url 'songs:edit_song' songID %}">Rediger sang</a></li>
    {% else %}
        <li class="breadcrumb-item"><a href="{% url 'songs:add_song' %}">Opprett sang</a></li>
    {% endif %}
{% endblock %}

{% block body %}
    <div class="">

        <div class="h1">
            Sang:
        </div>



        <div class="default-theme user-theme">

            <form method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-md-5 mb-3">
                        {{ form.title.label_tag }}
                        {{ form.title }}
                        {{ form.title.errors }}
                    </div>
                    <div class="col-md-5 mb-3">
                        {{ form.artist.label_tag }}
                        {{ form.artist }}
                        {{ form.artist.errors }}
                    </div>
                    <div class="col-md-2 mb-3">
                        {{ form.bpm.label_tag }}
                        <i class="lni-question-circle cursor-pointer custom-tooltip" data-toggle="tooltip" title="{{ form.bpm.help_text }}"></i>
                        <span class="ml-2" id="bmp"></span>
                        {{ form.bpm }}
                        <span class="text-muted small">Klikk for å beregne</span>
                        {{ form.bpm.errors }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-md mb-3">
                        {{ form.spotify_URL.label_tag }}
                        <i class="lni-question-circle cursor-pointer" data-toggle="tooltip" title="{{ form.spotify_URL.help_text }}"></i>
                        {{ form.spotify_URL }}
                        {{ form.spotify_URL.errors }}
                    </div>
                    <div class="col-md mb-3">
                        {{ form.spotify_URI.label_tag }}
                        <i class="lni-question-circle cursor-pointer" data-toggle="tooltip" title="{{ form.spotify_URI.help_text }}"></i>
                        {{ form.spotify_URI }}
                        <span class="error">{{ form.spotify_URI.errors }}</span>
                    </div>
                </div>
                <br>
                <div class="form-row">
                    {{ form.tags }}
                </div>

                <div class="row">
                    <div class="col-md-4 mt-4">
                        <a class="btn btn-dark btn-block text-light" href="{% url 'songs:all_songs' %}">Avbryt</a>
                    </div>
                    <div class="col mt-4">
                        <button type="submit" class="btn btn-secondary btn-block text-light">Lagre</button>
                    </div>
                </div>

            </form>

        </div>

    </div>
{% endblock %}

{% block script %}
    <script type="text/javascript">
        $(document).ready(function() {

            var count = 0;
            var msecsFirst = 0;
            var msecsPrevious = 0;
            var timeout = 2000;

            function TapForBPM(e) {
                timeSeconds = new Date;
                msecs = timeSeconds.getTime();
                if ((msecs - msecsPrevious) > timeout) {
                    count = 0;
                }

                if (count == 0) {
                    $('#bmp').html("First Beat")
                    msecsFirst = msecs;
                    count = 1;
                }
                else {
                    bpmAvg = 60000 * count / (msecs - msecsFirst);
                    $('#bmp').html(Math.round(bpmAvg))
                    count++;
                }
                msecsPrevious = msecs;
                return true;
            }


            // Initialize tooltip from bootstrap
            $(function () {
                $('[data-toggle="tooltip"]').tooltip()
            })

            $(document).ready(function() {
                document.onkeypress = TapForBPM;
                $(window).click(TapForBPM);
            })
        })

    </script>
{% endblock script %}