accounts/urls.py
# imports
from django.urls import path
from django.contrib.auth.views import LoginView
from django.views.generic import TemplateView

from accounts.forms import CustomAuthForm
from accounts import views
# End: imports -----------------------------------------------------------------

app_name = 'accounts' # Necessary for url naming. eg {% url 'accounts:signin' %}

urlpatterns = [
    #path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', TemplateView.as_view(template_name='accounts/login.html'), name='login'),
    #path('logout/', views.LogoutUserView.as_view(), name='logout'),
    #path('logout/', logout, {'template_name':'songs/home.html'}, name='logout'),
    #path('change_password/', views.ChangePasswordView.as_view(), name='change_password'),

    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.EditProfileView.as_view(), name='edit_profile'),
    path('profile/settings/', views.SettingsView.as_view(), name='settings'),
    path('profile/settings/theme/edit/<int:modelID>/', views.EditTheme.as_view(), name='edit_theme'),
    path('profile/settings/theme/add/', views.AddTheme.as_view(), name='add_theme'),

    #path('delete_user/', views.DeleteUserView.as_view(), name="delete_user"),

    path('spotify/callback/', views.callback, name="callback"),

    #path('spotify/connect/', views.SpotifyConnectView.as_view(), name="connect"),
]

courses/urls.py
# imports
from django.urls import path
from django.views.i18n import JavaScriptCatalog
from courses import views
# End: imports -----------------------------------------------------------------

app_name = 'courses'

urlpatterns = [
    # path(route, view, kwargs=None, name=None)
    path('all/', views.AllCoursesView.as_view(), name="all_courses"),
    path('add/', views.AddCourseView.as_view(), name="add_course"),
    path('<int:courseID>/', views.CourseView.as_view(), name="course_view"),
    path('delete/<int:courseID>/', views.DeleteCourseView.as_view(), name="delete_course"),
    path('edit/<int:courseID>/', views.EditCourseView.as_view(), name="edit_course"),
    path('duplicate/<int:courseID>/', views.DuplicateCourse.as_view(), name="duplicate_course"),
    path('export/<int:courseID>/', views.ExportView.as_view(), name="export_course"),
    path('spotify/create_playlist/<int:courseID>/', views.CreatePlaylistView.as_view(), name="create_playlist"),
]

events/urls.py
# imports
from django.urls import path

from events import views
# End: imports -----------------------------------------------------------------

app_name = 'events'

urlpatterns = [
    # path(route, view, kwargs=None, name=None)
    path('all/', views.AllEventsView.as_view(), name="all_events"),
    path('add/', views.AddEventView.as_view(), name="add_event"),
    path('<int:eventID>/', views.EventView.as_view(), name="event_view"),
    path('edit/<int:modelID>/', views.EditEventView.as_view(), name="edit_event"),
    path('signup/<int:modelID>/', views.EventSignup.as_view(), name="event_signup"),
]

info/urls.py
# imports
from django.urls import path
from info import views
from django.views.i18n import JavaScriptCatalog
# End: imports -----------------------------------------------------------------

app_name = 'info'

urlpatterns = [
    path('external/', views.external, name="external"),
    path('english/', views.english, name="english"),
    path('contact/', views.contact, name="contact"),
    path('about/', views.about, name="about"),
    path('hall_times/', views.hall_times, name="hall_times"),
    path('faq/', views.faq, name="faq"),
]

music_library/urls.py
from songs import views
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.views.i18n import JavaScriptCatalog


app_name = 'root'


urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', views.HomeView.as_view(), name="home"),
    path('forbidden/', views.ForbiddenView.as_view(), name="forbidden"),

    path('songs/', include('songs.urls')),
    path('account/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('courses/', include('courses.urls')),
    path('videos/', include('videos.urls')),
    path('info/', include('info.urls')),
    path('wiki/', include('wiki.urls')),
    path('events/', include('events.urls')),

    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('tinymce/', include('tinymce.urls')),
    path('select2/', include('django_select2.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
# imports
from django import forms
from django.db.models import Q
from django.forms.widgets import PasswordInput, TextInput
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import get_user_model

from accounts.models import *
from accounts import models as account_models

User = get_user_model()

# End: imports -----------------------------------------------------------------

class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = [
            'email',
            'first_name',
            'last_name',
            'phone_number',
        ]

    def __init__(self, *args, **kwargs):
        super(type(self), self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

        self.fields['password1'].help_text = 'Your password cant be too similar to your other personal information. Your password must contain atleast 8 characters. Your password cant be a commonly used password and cant be entierly numeric.'

class EditUserForm(forms.ModelForm):

    required_css_class = "required font-bold"

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'phone_number',
        ]
        labels = {
            'first_name': 'Fornavn',
            'last_name': 'Etternavn',
            'phone_number': 'Mobilnummer',
        }


    def __init__(self, *args, **kwargs):
        super(type(self), self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

class InstructorForm(forms.ModelForm):

    required_css_class = "required font-bold"

    class Meta:
        model = account_models.Instructor
        fields = [
            'user',
            'type',
        ]

    def __init__(self, *args, **kwargs):
        super(InstructorForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})



class SettingsForm(forms.ModelForm):

    required_css_class = "required font-bold"

    class Meta:
        model = account_models.Settings
        exclude = ['user']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(type(self), self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

        themes = Theme.objects.filter( Q(user=None) | Q(user=user) )

        self.fields['account_theme'].queryset = themes
        self.fields['video_theme'].queryset = themes
        self.fields['course_theme'].queryset = themes
        self.fields['song_theme'].queryset = themes
        self.fields['wiki_theme'].queryset = themes
        self.fields['event_theme'].queryset = themes
        self.fields['main_theme'].queryset = themes
        self.fields['input_theme'].queryset = themes
        self.fields['footer_theme'].queryset = themes

class ThemeForm(forms.ModelForm):

    required_css_class = "required font-bold"

    class Meta:
        model = account_models.Theme
        fields = [
            'name',
            'background_color',
            'text_color',
            'link_color',
            'link_hover_color',
        ]

    def __init__(self, *args, **kwargs):
        super(type(self), self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})


# Possible to customise login:
class CustomAuthenticationForm(AuthenticationForm): # Not currently in use. Can be passed to login view
    error_messages = dict(AuthenticationForm.error_messages) # Inherit from parent. invalid_login and inactive

    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise forms.ValidationError(self.error_messages['inactive'], code='inactive')

        if not user.is_authenticated:
            raise forms.ValidationError(self.error_messages['invalid_login'], code='invalid_login')

class CustomAuthForm(AuthenticationForm):
    # Inherited fields:
    # username
    # password
    username = forms.CharField(widget=TextInput(attrs={'class':'form-control', 'placeholder': 'Email'}))
    password = forms.CharField(widget=PasswordInput(attrs={'class': 'form-control', 'placeholder':'Password'}))


class CustomPasswordChangeForm(PasswordChangeForm):
    # Inherited fields:
    # old_password
    # new_password1
    # new_password2

    class Meta:
        model = User

    def __init__(self, *args, **kwargs):
        super(type(self), self).__init__(*args, **kwargs)
        self.fields['old_password'].widget.attrs.update({'class': 'form-control'})
        self.fields['new_password1'].widget.attrs.update({'class': 'form-control'})
        self.fields['new_password2'].widget.attrs.update({'class': 'form-control'})

accounts/views.py
# imports
import spotipy.oauth2 as oauth2

from django.views import View
from django.db.models import Q
from django.urls import reverse
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth import views as auth_views
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.admin.views.decorators import staff_member_required, user_passes_test

from accounts import models as account_models
from accounts import forms as account_forms
from wiki import views as wiki_views

User = get_user_model()
# End: imports -----------------------------------------------------------------

profile_dec = [
    login_required,
]

@method_decorator(profile_dec, name='dispatch')
class ProfileView(View):
    template = "accounts/profile.html"

    def get(self, request, *args, **kwargs):
        courses = request.user.getCourses()
        return render(request, self.template, {'courses': courses})



@method_decorator(profile_dec, name='dispatch')
class EditProfileView(View):
    template = "accounts/edit_profile.html"
    form_class = account_forms.EditUserForm

    def get(self, request, *args, **kwargs):
        form = self.form_class(instance=request.user)
        return render(request, self.template, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile')
        else:
            return render(request, self.template, {'form': form})

class SignUpView(View):
    template = "accounts/registration_form.html"
    form_class = account_forms.SignUpForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(email=email, password=raw_password)
            login(request, user)
            return redirect('home')
        else:
            return render(request, self.template, {'form': form})


@method_decorator(profile_dec, name='dispatch')
class DeleteUserView(View):

    def get(self, request, *args, **kwargs):
        request.user.delete()
        logout(request)
        return redirect('home')


@method_decorator(profile_dec, name='dispatch')
class LogoutUserView(View):

    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('accounts:login')

@method_decorator(profile_dec, name='dispatch')
class SettingsView(View):
    template = "accounts/settings.html"
    form_class = account_forms.SettingsForm

    def get(self, request, *args, **kwargs):
        settings, created = account_models.Settings.objects.get_or_create(user=request.user)
        form = self.form_class(instance=settings, user=request.user)
        themes = form.fields["main_theme"].queryset

        return render(request, self.template, {'form': form, 'themes': themes})

    def post(self, request, *args, **kwargs):
        settings, created = account_models.Settings.objects.get_or_create(user=request.user)
        form = self.form_class(request.POST, instance=settings, user=request.user)
        themes = form.fields["main_theme"].queryset

        if form.is_valid():
            settings = form.save()
            return redirect("accounts:profile")
        else:
            return render(request, self.template, {'form': form, 'themes': themes})



addTheme_dec = [
    login_required,
    permission_required('accounts.add_theme', login_url='forbidden')
]
@method_decorator(addTheme_dec, name='dispatch')
class AddTheme(wiki_views.GenericAddModel):
    template = 'accounts/theme_form.html'
    form_class = account_forms.ThemeForm
    redirect_name = 'accounts:settings'



editTheme_dec = [
    login_required,
    permission_required('accounts.change_theme', login_url='forbidden')
]
class EditTheme(wiki_views.GenericEditModel):
    template = 'accounts/theme_form.html'
    form_class = account_forms.ThemeForm
    redirect_name = 'accounts:settings'
    model = account_models.Theme

    def get(self, request, modelID, *args, **kwargs):
        if request.user != self.model.objects.get(id=modelID).user:
            return redirect('forbidden')
        return super(type(self), self).get(request, modelID, *args, **kwargs)

    def post(self, request, modelID, *args, **kwargs):
        if request.user != self.model.objects.get(id=modelID).user:
            return redirect('forbidden')
        return super(type(self), self).post(request, modelID, *args, **kwargs)




@method_decorator(profile_dec, name='dispatch')
class ChangePasswordView(View):
    template = "accounts/change_password.html"
    form_class = account_forms.CustomPasswordChangeForm

    def get(self, request, *args, **kwargs):
        form = self.form_class(request.user)
        return render(request, self.template, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            return redirect("accounts:profile")
        return render(request, self.template, {'form': form})



class SpotifyConnectView(View):
    template = "accounts/spotify_connect.html"

    def post(self, request, *args, **kwargs):

        cache_path = settings.SPOTIFY_CACHE_PATH + '.spotify-token-' + request.user.email
        sp_oauth = oauth2.SpotifyOAuth(settings.SPOTIFY_CLIENT_ID, settings.SPOTIFY_CLIENT_SECRET, settings.SPOTIFY_REDIRECT_URI, scope=settings.SPOTIFY_SCOPE, cache_path=cache_path)

        token_info = sp_oauth.get_cached_token()

        if not token_info:
            auth_url = sp_oauth.get_authorize_url()
            try:
                print(auth_url)
                import webbrowser
                webbrowser.open(auth_url+'&show_dialog=true')
            except Exception as e:
                print(e)

        return redirect("accounts:profile")

def callback(request):
    response = request.build_absolute_uri()
    sp_oauth = oauth2.SpotifyOAuth(settings.SPOTIFY_CLIENT_ID, settings.SPOTIFY_CLIENT_SECRET, settings.SPOTIFY_REDIRECT_URI, scope=settings.SPOTIFY_SCOPE)

    sp_token, created = account_models.SpotifyToken.objects.get_or_create(user=request.user)

    code = sp_oauth.parse_response_code(response)
    token_info = sp_oauth.get_access_token(code)
    sp_token.addInfo(token_info)

    return redirect('accounts:profile')

accounts/templates/accounts/change_password.html
{% extends 'songs/base.html' %}
{% load static %}
{% block title %}{{ user.get_full_name }}{% endblock title %}

{% block head %}
    <link rel="stylesheet" href="{% static "accounts/account_styles.css" %}">

    <style media="screen">
        #form {
            max-width: 35em;
        }
        {{ request.user.settings.account_theme.as_css }}
    </style>
{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'accounts:profile' %}">Min profil</a></li>
    <li class="breadcrumb-item"><a href="{% url 'accounts:change_password' %}">Bytt passord</a></li>
{% endblock %}

{% block body %}
    <div id="form">
        <h1>Bytt passord:</h1>
        <form class="container default-theme user-theme" method="POST">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {% for error in field.errors %}
                        <div class="error">{{ error }}</div>
                    {% endfor %}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-block btn-primary">Save</button>
        </form>
    </div>
{% endblock %}

{% block scriptblock %}
    <script type="text/javascript">
        $(document).ready(function() {

        })
    </script>
{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'songs/base.html' %}
{% load static %}
{% block title %}{{ request.user }}{% endblock title %}

{% block head %}
    <link rel="stylesheet" href="{% static "accounts/account_styles.css" %}">

    <style media="screen">

        {{ request.user.settings.account_theme.as_css }}

        #form {
            max-width: 35em;
        }
    </style>
{% endblock head %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'accounts:profile' %}">Min profil</a></li>
    <li class="breadcrumb-item"><a href="{% url 'accounts:edit_profile' %}">Rediger profil</a></li>
{% endblock %}

{% block body %}
    <div id="form" class="default-theme user-theme">
        <h1>Rediger profil:</h1>
        <!-- Edit user (form) -->
        <form method="POST"> <!-- Bootstrap -->
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group"> <!-- Bootstrap -->
                    {{ field.label_tag }}
                    {{ field }}
                    <div class="text-muted small">
                        {{ field.help_text }}
                    </div>
                    {% for error in field.errors %}
                        <div class="text-danger">{{ error }}</div>
                    {% endfor %}
                </div>
            {% endfor %}

            <div class="row">
                <div class="col-sm-4 mt-2">
                    <a class="btn btn-secondary btn-block text-light" href="{% url 'accounts:profile' %}">Avbryt</a>
                </div>
                <div class="col mt-2">
                    <button type="submit" class="btn btn-primary btn-block text-light">Lagre</button>
                </div>
            </div>


        </form> <!-- End: Edit user (form) -->


    </div>

    <br><br><br> <!-- Quickfix footer -->
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'songs/base.html' %}
{% load static %}
{% load account %}
{% load socialaccount %}

{% block title %}Login{% endblock title %}

{% block head %}
    <link rel="stylesheet" href="{% static "accounts/account_styles.css" %}">
    <style media="screen">
        .default-theme {
            min-width: 220px;
            max-width: 500px;
        }
    </style>
{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'accounts:login' %}">Logg inn</a></li>
{% endblock %}

{% block body %}
    {% if user.is_authenticated %}
        <h2>Du er allerede logget inn</h2>
    {% else %}
        <div class="row">
            <div class="col">
                <div class="default-theme">

                    <h2>Logg inn:</h2>

                    <a class="btn btn-danger" href="{% provider_login_url "google" %}">
                        <img src="https://img.icons8.com/color/48/000000/google-logo.png">
                        Logg inn med Google
                    </a>

                </div>
            </div>
        </div>
        <br>

        <br>
    {% endif %}
{% endblock %}

{% block scriptblock %}
    <script type="text/javascript">
        $(document).ready(function() {

        })
    </script>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'songs/base.html' %}
{% block title %}{{ request.user }}{% endblock %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static "accounts/account_styles.css" %}">

    <style media="screen">

        #my-courses {
            max-height: 200px;
        }

        #panels {
            max-height: 100%;
            overflow-y: auto;
        }

        #panels {
            overflow-y: auto;
            max-height: 40vh;

        }

        {{ request.user.settings.account_theme.as_css }}

    </style>
{% endblock head %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'accounts:profile' %}">Min profil</a></li>
{% endblock %}

{% block body %}
    <div class="">

        <div id="title" class="text-center">
            <h1>{{ user }}</h1>
        </div>

        <div class="row mt-2">
            <div class="col-md-7 mt-2">
                <div class="default-theme user-theme">
                    <h4>Personlig informasjon:</h4>
                    <p>
                        <div>Email: {{ user.email }}</div>
                        <div>Mobil: {{ user.phone_number }}</div>
                        <hr class="border border-light">
                        <div>Antall kurs som lead: {{ user.lead_courses.count }}</div>
                        <div>Antall kurs som follow: {{ user.follow_courses.count }}</div>
                    </p>
                </div>
            </div>

            <div class="col-md mt-2">

                <div class="nav nav-tabs" role="tablist">
                    <a class="nav-item nav-link" id="event-tab" data-toggle="tab" href="#event-panel" role="tab" aria-controls="event-panel" aria-selected="false">Mine events</a>

                    {% if perms.course.view_course %}
                        <a class="nav-item nav-link active" id="course-tab" data-toggle="tab" href="#course-panel" role="tab" aria-controls="course-panel" aria-selected="true">Mine kurs</a>
                    {% endif %}
                </div>

                <div id="panels" class="tab-content p-2 default-theme user-theme rounded-top">
                    <div class="tab-pane fade" id="event-panel" role="tabpanel" aria-labelledby="event-tab">
                        {% for event in request.user.events.all %}
                            <div class="">
                                <a href="{% url 'events:event_view' event.id %}">{{ event }}</a>
                            </div>
                        {% endfor %}
                    </div>
                    {% if perms.course.view_course %}
                        <div class="tab-pane fade show active" id="course-panel" role="tabpanel" aria-labelledby="course-tab">
                            {% for course in request.user.getCourses %}
                                <div class="">
                                    <a href="{% url 'courses:course_view' course.id %}">{{ course }}</a>
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>

            <!--
            <div class="col-md mt-2">

                <div class="btn btn-dark btn-block btn-sm text-light" data-toggle="collapse" data-target="#my-courses" aria-expanded="false" aria-controls="my-courses">
                    Mine kurs ({{ courses.count }})
                    <i class="lni-chevron-down cursor-pointer" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
                </div>

                <div id="my-courses" class="collapse">
                    <div class="overflow-auto default-theme user-theme rounded-top p-3">
                        {% for course in courses %}
                            <div class="">
                                <a href="{% url 'courses:course_view' course.id %}">{{ course }}</a>
                            </div>
                        {% endfor %}
                    </div>
                </div>

            </div>
            -->
        </div>




        <div class="text-right mt-4">
            <a class="btn btn-secondary text-light" href="{% url 'accounts:settings' %}">Innstillinger</a>
            <a class="btn btn-secondary text-light" href="{% url 'accounts:edit_profile' %}">Rediger profil</a>
            <a class="btn btn-danger text-light" href="/accounts/logout">Logg ut</a>
        </div>

    </div>
{% endblock %}

accounts/templates/accounts/settings.html
{% extends 'songs/base.html' %}
{% block title %}{{ request.user }}{% endblock %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static "accounts/account_styles.css" %}">

    <style media="screen">
        .default-theme {
            min-width: 200px;
            max-width: 500px;
        }
        {{ request.user.settings.account_theme.as_css }}
    </style>
{% endblock head %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'accounts:profile' %}">Min profil</a></li>
    <li class="breadcrumb-item"><a href="{% url 'accounts:settings' %}">Innstillinger</a></li>
{% endblock %}

{% block body %}

    <div class="">

        <div class="row m-0">

            <div class="col-md p-0">
                <div class="default-theme user-theme">
                    <h1>Innstillinger:</h1>

                    <form class="" method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            {{ field.label_tag }}
                            {{ field }}
                            <div class="small text-muted font-italic">
                                {{ field.help_text }}
                            </div>
                            <div class="text-danger">
                                {{ field.errors }}
                            </div>
                        {% endfor %}

                        <div class="row m-0">
                            <div class="col-md-4 p-0 mt-4">
                                <a class="btn btn-secondary btn-block text-light" href="{% url 'accounts:profile' %}">Avbrut</a>
                            </div>
                            <div class="col mt-4">
                                <button type="submit" class="btn btn-primary btn-block text-light">Lagre</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="col-md p-0">
                <div class="">
                    <div class="h2">
                        Temaer:
                    </div>


                    <div class="">
                        {% for theme in themes %}
                            <div id="theme-{{theme.id}}" class="p-1 m-1 rounded" style="background-color:{{theme.background_color}};color:{{theme.text_color}}">
                                {{theme}}
                                <a href="#" style="color:{{theme.link_color}};" onmouseover="this.style.color='{{theme.link_hover_color}}';" onmouseout="this.style.color='{{theme.link_color}}'">
                                    Link
                                </a>
                                {% if theme.user == request.user %}
                                    <a class="bg-light text-dark rounded px-1 float-right" href="{% url 'accounts:edit_theme' theme.id %}">Rediger</a>
                                {% endif %}

                            </div>
                        {% endfor %}

                    </div>

                    <div class="">
                        Ingen temaer du liker? -->
                        <a class="btn btn-dark btn-sm text-light" target="_blank" href="{% url 'accounts:add_theme' %}">Lag nytt tema</a>

                    </div>

                </div>
            </div>


        </div>

    </div>


{% endblock %}

accounts/templates/accounts/theme_form.html
{% extends 'songs/base.html' %}
{% block title %}{{ request.user }}{% endblock %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static "accounts/account_styles.css" %}">

    <style media="screen">
        {{ request.user.settings.account_theme.as_css }}
    </style>
{% endblock head %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'accounts:profile' %}">Min profil</a></li>
    <li class="breadcrumb-item"><a href="{% url 'accounts:settings' %}">Innstillinger</a></li>
    {% if modelID %}
        <li class="breadcrumb-item"><a href="{% url 'accounts:edit_theme' form.instance.id %}">{{form.instance}}</a></li>
    {% else %}
        <li class="breadcrumb-item"><a href="{% url 'accounts:add_theme' %}">Opprett tema</a></li>
    {% endif %}
{% endblock %}

{% block body %}
    <div class="body-wrapper">

        <div class="default-theme user-theme">
            <div class="h1">
                Tema:
            </div>

            <form class="" method="post">
                {% csrf_token %}
                {% for field in form %}
                    {{ field.label_tag }}
                    {{ field }}
                    <div class="small text-muted font-italic">
                        {{ field.help_text }}
                    </div>
                    <div class="text-danger">
                        {{ field.errors }}
                    </div>
                {% endfor %}

                <div class="row m-0">
                    <div class="col-md-4 p-0 mt-4">
                        <a class="btn btn-secondary btn-block text-light" href="{% url 'accounts:settings' %}">Avbryt</a>
                    </div>
                    <div class="col mt-4">
                        <button type="submit" class="btn btn-primary btn-block text-light">Lagre</button>
                    </div>
                </div>
            </form>
        </div>

    </div>
{% endblock %}