courses/urls.py
# imports
from django.urls import path
from django.views.i18n import JavaScriptCatalog
from courses import views
# End: imports -----------------------------------------------------------------

app_name = 'courses'

urlpatterns = [
    # path(route, view, kwargs=None, name=None)
    path('all/', views.AllCoursesView.as_view(), name="all_courses"),
    path('add/', views.AddCourseView.as_view(), name="add_course"),
    path('<int:courseID>/', views.CourseView.as_view(), name="course_view"),
    path('delete/<int:courseID>/', views.DeleteCourseView.as_view(), name="delete_course"),
    path('edit/<int:courseID>/', views.EditCourseView.as_view(), name="edit_course"),
    path('duplicate/<int:courseID>/', views.DuplicateCourse.as_view(), name="duplicate_course"),
    path('export/<int:courseID>/', views.ExportView.as_view(), name="export_course"),
    path('spotify/create_playlist/<int:courseID>/', views.CreatePlaylistView.as_view(), name="create_playlist"),
]

info/urls.py
# imports
from django.urls import path
from info import views
from django.views.i18n import JavaScriptCatalog
# End: imports -----------------------------------------------------------------

app_name = 'info'

urlpatterns = [
    path('external/', views.external, name="external"),
    path('english/', views.english, name="english"),
    path('contact/', views.contact, name="contact"),
    path('about/', views.about, name="about"),
    path('hall_times/', views.hall_times, name="hall_times"),
    path('faq/', views.faq, name="faq"),
]

music_library/urls.py
from songs import views
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.views.i18n import JavaScriptCatalog


app_name = 'root'


urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', views.HomeView.as_view(), name="home"),
    path('forbidden/', views.ForbiddenView.as_view(), name="forbidden"),

    path('songs/', include('songs.urls')),
    path('account/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('courses/', include('courses.urls')),
    path('videos/', include('videos.urls')),
    path('info/', include('info.urls')),
    path('wiki/', include('wiki.urls')),
    path('events/', include('events.urls')),

    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('tinymce/', include('tinymce.urls')),
    path('select2/', include('django_select2.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

songs/urls.py
# imports
from django.urls import path
from django.views.i18n import JavaScriptCatalog
from songs import views
# End: imports -----------------------------------------------------------------

app_name = 'songs'

urlpatterns = [
    path('all/', views.AllSongsView.as_view(), name="all_songs"),
    path('add/', views.AddSongView.as_view(), name="add_song"),
    path('edit/<int:songID>', views.EditSongView.as_view(), name="edit_song"),
    path('delete/<int:songID>', views.DeleteSongView.as_view(), name="delete_song"),
    path('bpm_calc/', views.BPMView.as_view(), name="bpm_calc"),

    path('tags/add', views.AddTag.as_view(), name="add_tag"),
    path('tags/edit/<int:tagID>', views.EditTag.as_view(), name="edit_tag"),
    path('tags/all', views.AllTags.as_view(), name="all_tags"),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

courses/models.py
# imports
from django.db import models
from django.conf import settings
from django.utils import timezone


# End: imports -----------------------------------------------------------------
semesters = ['------']
v = [f"V{year}" for year in range(2000, 2100)]
h = [f"H{year}" for year in range(2000, 2100)]
semesters.extend(v)
semesters.extend(h)
SEMESTER_CHOICES = [(i, semesters[i]) for i in range(len(semesters))]

class Course(models.Model):
    title = models.CharField(max_length=140, null=True, blank=False, verbose_name="Tittel")
    place = models.CharField(max_length=140, null=True, blank=True, verbose_name="Sted")
    date = models.DateField(null=True, blank=True, verbose_name="Dato")
    start = models.DateTimeField(null=True, blank=True)
    end = models.DateTimeField(null=True, blank=True, verbose_name="Slutt")
    lead = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name="lead_courses", verbose_name="Instruktør (lead)")
    follow = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name="follow_courses", verbose_name="Instruktør (follow)")
    comments = models.TextField(null=True, blank=True, verbose_name="Kommentarer")
    tags = models.ManyToManyField('songs.Tag', blank=True)
    semester_char = models.CharField(max_length=5, null=True, blank=True)
    external = models.BooleanField(default=False, verbose_name="Eksternkurs")
    bulk = models.PositiveIntegerField(null=True, blank=True, verbose_name="Bolk")
    day = models.PositiveIntegerField(null=True, blank=True, verbose_name="Dag")

    last_edited = models.DateTimeField(null=True, blank=True, editable=False, verbose_name="Sist redigert")
    last_editor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, editable=False, related_name="last_edited_courses", verbose_name="Sist redigert av")
    created = models.DateTimeField(null=True, blank=True, editable=False, verbose_name="Opprettet")
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, editable=False, related_name="created_courses", verbose_name="Opprettet av")

    # NOTE: Under development
    # instructors = models.ManyToManyField(settings.AUTH_USER_MODEL)
    instructors = models.ManyToManyField(settings.AUTH_USER_MODEL, through='accounts.Instructor', blank=True)
    semester_choice = models.IntegerField(choices=SEMESTER_CHOICES, null=True, blank=True)


    class Meta:
        ordering = ['date', 'bulk', 'day', 'title']
        verbose_name = "Kurs"
        verbose_name_plural = "Kurs"

    def __str__(self):
        if self.external:
            return f"{self.semester_char} {self.title}"
        else:
            return f"{self.semester_char}, Bolk {self.bulk}, Dag {self.day}"

    def getSemester(self):
        semesters = ['Vår', 'Høst']
        if self.date:
            i = (self.date.month-1) // 6 # Calculates first (0) or second (1) half of year
            return f"{semesters[i]} {self.date.year}"
        else:
            return None

    def getTitle(self):
        return self.title or None

    def getDate(self):
        try: return self.date.strftime("%d.%m.%y")
        except: return None

    def getStart(self):
        try: return self.start.strftime("%H:%M")
        except: return None

    def getEnd(self):
        try: return self.end.strftime("%H:%M")
        except: return None

    def getTags(self):
        return [title[0] for title in self.tags.all().values_list('title') ]

    def save(self, *args, **kwargs):
        if not self.id:
            self.created = timezone.now()
        self.last_edited = timezone.now()

        if self.date:
            semesters = ['V', 'H']
            i = (self.date.month-1) // 6 # Calculates first (0) or second (1) half of year
            self.semester_char = f"{semesters[i]}{self.date.year}"


        return super(type(self), self).save(*args, **kwargs)



class Section(models.Model):
    title = models.CharField(max_length=140, null=True, blank=False, verbose_name="Tittel")
    course = models.ForeignKey('courses.Course', on_delete=models.CASCADE, null=True, blank=True, related_name="sections", verbose_name="Kurs")
    description = models.TextField(null=True, blank=True, verbose_name="Beskrivelse")
    start = models.TimeField(null=True, blank=True)
    # duration = models.FloatField(null=True, blank=False, verbose_name="Varighet")
    duration = models.FloatField(default=7.5, null=True, blank=False, verbose_name="Varighet")
    song = models.ForeignKey('songs.Song', on_delete=models.SET_NULL, null=True, blank=True, related_name="sections", verbose_name="Sang")
    song2 = models.ForeignKey('songs.Song', on_delete=models.SET_NULL, null=True, blank=True, related_name="sections_song2", verbose_name="Sang")
    video = models.ForeignKey('videos.Video', on_delete=models.SET_NULL, null=True, blank=True, related_name="sections", verbose_name="Video")
    nr = models.IntegerField(null=True, blank=True)

    class Meta:
        ordering = ['nr']
        verbose_name = "Kurs-seksjon"
        verbose_name_plural = "Kurs-seksjoner"

    def __str__(self):
        return "Section ({}) in course: {}".format(self.getNr(), self.getCourse())

    def getCourse(self):
        return self.course or None

    def getNr(self):
        return self.nr or None

    def getStart(self):
        return self.start.strftime("%H:%M")

    def getSong(self):
        return self.song or None

courses/forms.py
# imports
import json

from django import forms
from django.contrib.admin.widgets import FilteredSelectMultiple
from django.contrib.auth import get_user_model

from songs import models as song_models
from videos import models as video_models
from courses import models as course_models
from django_select2 import forms as select2_forms

User = get_user_model()

# End: imports -----------------------------------------------------------------

DATE_FORMATS = [
    "%d-%m-%y", "%d-%m-%Y", # 26-02-97  26-02-1997
    "%d/%m/%y", "%d/%m/%Y", # 26/02/97  26/02/1997
    "%d:%m:%y", "%d:%m:%Y", # 26:02:97  26:02:1997
    "%d.%m.%y", "%d.%m.%Y", # 26.02.97  26.02.1997
    "%d,%m,%y", "%d,%m,%Y", # 26,02,97  26,02,1997

    "%d/%m-%y", "%d/%m-%Y", # 26/02-97  26/02-1997
    "%d %m %y", "%d %m %Y", # 26 02 97  26 02 1997
]

TIME_FORMATS = [
    '%H:%M',        # '14:30'
    '%H.%M',        # '14.30'
    '%H %M',        # '14 30'
]

MIN_FORMATS = [
    "%M"
]

class CourseForm(forms.ModelForm):
    q = song_models.Tag.getQueryset(["course"])

    tags = forms.ModelMultipleChoiceField(queryset=q, widget=FilteredSelectMultiple(verbose_name="tags", is_stacked=False), required=False)
    date = forms.DateField(input_formats=DATE_FORMATS, required=False, label="Dato")
    start = forms.DateTimeField(input_formats=TIME_FORMATS, required=False, label="Start")
    end = forms.DateTimeField(input_formats=TIME_FORMATS, required=False, label="Slutt")

    required_css_class = 'required font-bold'
    # instructors = forms.ModelMultipleChoiceField(queryset=User.objects.all(), widget=select2_forms.Select2MultipleWidget)

    class Media:
        css = {
            'all': ['admin/css/widgets.css'], # 'css/uid-manage-form.css'
        }
        # Adding this javascript is crucial
        js = ['/admin/jsi18n/']

    class Meta:
        model = course_models.Course
        fields = [
            'title',
            'place',
            'date',
            'start',
            'end',
            'lead',
            'follow',
            'comments',
            'tags',
            'instructors',
            'bulk',
            'day',
            'external',
        ]

    def __init__(self, *args, **kwargs):
        super(type(self), self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

        # self.fields['external'].widget.attrs.update({'class': ''})

        self.fields['title'].widget.attrs.update({'placeholder': 'Tittel'})

        self.fields['start'].widget.attrs.update({'placeholder': 'hh:mm'})
        self.fields['start'].widget.format = "%H:%M"

        self.fields['date'].widget.attrs.update({'placeholder': 'dd.mm.yy'})
        self.fields['date'].widget.format = "%d.%m.%y"

        self.fields['end'].widget.attrs.update({'placeholder': 'hh:mm'})
        self.fields['end'].widget.format = "%H:%M"

        self.fields['comments'].widget.attrs.update({'rows': '7'})



class SectionForm(forms.ModelForm):
    # duration = forms.TimeField(input_formats=MIN_FORMATS, required=False)
    required_css_class = 'required font-bold'

    class Meta:
        model = course_models.Section
        exclude = ['nr']
        widgets = {
            'song': select2_forms.Select2Widget(),
            'song2': select2_forms.Select2Widget(),
        }

    def __init__(self, *args, **kwargs):
        super(type(self), self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

        self.fields['duration'].widget.attrs.update({'placeholder': 'min'})
        # self.fields['duration'].widget.format = "%M"

        self.fields['start'].widget.attrs.update({'placeholder': 'hh:mm', 'readonly': '1'})
        self.fields['start'].widget.format = "%H:%M"

        self.fields['description'].widget.attrs.update({'class': 'tinymce'})


class CourseFilterForm(forms.Form):
    search = forms.CharField(required=False, label="Søk")
    tag = forms.ChoiceField(required=False, widget=select2_forms.Select2Widget())
    # tag = forms.ChoiceField(required=False)
    lead = forms.ChoiceField(required=False, widget=select2_forms.Select2Widget(), label="Instruktør (lead)")
    # lead = forms.ChoiceField(required=False, label="Instruktør (lead)")
    follow = forms.ChoiceField(required=False, widget=select2_forms.Select2Widget(), label="Instruktør (follow)")
    bulk = forms.IntegerField(required=False, label="Bolk")
    day = forms.IntegerField(required=False, label="Dag")
    semester_char = forms.CharField(required=False, label="Semester")
    external = forms.BooleanField(initial=False, required=False, label="Eksternkurs")

    def __init__(self, *args, **kwargs):
        super(type(self), self).__init__(*args, **kwargs)
        for field in self.fields:
            # pass
            self.fields[field].widget.attrs.update({'class': 'course-filter form-control'})

        self.fields['external'].widget.attrs.update({'class': 'invisible'})

        self.fields['search'].widget.attrs.update({'placeholder': 'Søk på tittel...', 'autofocus': True})
        self.fields['semester_char'].widget.attrs.update({'placeholder': 'Eks: H2019, V2020',})

        # self.fields['tag'].choices = [(-1, '-----')]
        self.fields['tag'].choices += [(tag.id, tag.title) for tag in song_models.Tag.getQueryset(["course"])]
        self.fields['tag'].widget.attrs.update({'class': 'form-control course-filter'})

        # self.fields['lead'].choices = [(-1, '-----')]
        self.fields['lead'].choices += [(lead.id, lead) for lead in User.objects.all()]

        # self.fields['follow'].choices = [(-1, '-----')]
        self.fields['follow'].choices += [(follow.id, follow) for follow in User.objects.all()]

courses/templates/courses/add_course_form.html
{% extends 'songs/base.html' %}
{% block title %}Add course{% endblock %}
{% load static %}

{% block head %}
    <script type="text/javascript" src="{% url 'songs:javascript-catalog' %}"></script>

    {{ form.media }}

    <link rel="stylesheet" href="{% static "courses/course_styles.css" %}">

    <style media="screen">
        .section {
            background-color: rgba(100, 180, 160, 0.5);
            margin-bottom: 1em;
        }
    </style>
{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'courses:add_course' %}">Rediger Kurs</a></li>
{% endblock %}

{% block body %}
<h1>Rediger Kurs</h1>

<form method="post">
    {% csrf_token %}
    <div id="addCourseForm">
        <div class="form-row">
            <div class="form-group col-md">
                {{ addCourseForm.title.label }}
                {{ addCourseForm.title }}
            </div>
            <div class="form-group col-md-2">
                {{ addCourseForm.start.label }}
                {{ addCourseForm.start }}
            </div>
            <div class="form-group col-md-1">
                {{ addCourseForm.duration.label }}
                {{ addCourseForm.duration }}
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md">
                {{ addCourseForm.lead.label }}
                {{ addCourseForm.lead }}
            </div>
            <div class="form-group col-md">
                {{ addCourseForm.follow.label }}
                {{ addCourseForm.follow }}
            </div>
        </div>
    </div>

    <br>

    {{ sectionFormTemplate.title }}

    <div class="d-none">
        <div id="sectionFormTemplate" class="jumbotron section">
            <div class="form-row">
                <div class="form-group col-md-3">
                    {{ sectionFormTemplate.title.label }}
                    {{ sectionFormTemplate.title }}
                </div>
                <div class="form-group col-md-2">
                    {{ sectionFormTemplate.start.label }}
                    {{ sectionFormTemplate.start }}
                </div>
                <div class="form-group col-md-1">
                    {{ sectionFormTemplate.duration.label }}
                    {{ sectionFormTemplate.duration }}
                </div>
                <div class="form-group col-md-2">
                    {{ sectionFormTemplate.song.label }}
                    {{ sectionFormTemplate.song }}
                </div>
                <div class="form-group col-md-2">
                    {{ sectionFormTemplate.video.label }}
                    {{ sectionFormTemplate.video }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-10">
                    {{ sectionFormTemplate.text.label }}
                    {{ sectionFormTemplate.text }}
                </div>
            </div>
            <button class="btn btn-danger float-right" id="btn-remove-section${i}" onclick="removeSection(this)" type="button" name="button" >
                <img src="https://img.icons8.com/material-sharp/24/000000/minus.png">
                Remove
            </button>
        </div>
    </div>


    <div id="dynamic-sections">
        <input id="sectionCount" type="hidden" readonly name="sectionCount" value="0">
    </div>

    <button class="btn btn-secondary" id="btn-add-section" type="button" name="button" >
        <img src="https://img.icons8.com/material-rounded/25/22BB30/plus-math.png">
        New section
    </button>

    <br>
    <br>

    <button class="btn btn-block btn-dark" type="submit">Save</button>
</form>

{% endblock %}

{% block script %}
    <script type="text/javascript">

        function removeSection(element) {
            var sectionID = element.id.slice(-1)
            $(`#section${sectionID}`).remove()
        }
        console.log($("#sectionFormTemplate").html())



        $(document).ready(function() {
            //
            // var sectionFormTemplate = $("#sectionFormTemplate")
            // console.log(sectionFormTemplate.html())
            //
            // console.log($("#sectionFormTemplate").html())
            // console.log($("#sectionFormTemplate").html().replace("_sectionID", "12345678"))
            // sectionFormTemplate = sectionFormTemplate.html().replace("sectionID", "12345678")

            //console.log(sectionFormTemplate)

            function create_section_form(i) {
                return `
                <div id="section${i}" class="jumbotron section">
                    <div class="form-row">
                        <div class="form-group col-md-3">
                            <label for="title${i}">Title</label>
                            <input type="text" name="title${i}" class="form-control" id="title${i}" placeholder="Title">
                        </div>
                        <div class="form-group col-md-2">
                            <label for="start${i}">Start</label>
                            <input type="text" name="start${i}" class="form-control" id="start${i}" placeholder="">
                        </div>
                        <div class="form-group col-md-1">
                            <label for="duration${i}">Duration</label>
                            <input type="text" name="duration${i}" class="form-control" id="duration${i}" placeholder="min">
                        </div>
                        <div class="form-group col-md-2">
                            <label for="song${i}">Song</label>
                            <select name="song${i}" class="form-control" id="song${i}">
                                <option value="-1" selected="">---------</option>
                                {% for song in songs %}
                                    <option value="{{ forloop.counter }}">{{ song.title }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group col-md-2">
                            <label for="video${i}">Video</label>
                            <select name="video${i}" class="form-control" id="video${i}">
                                <option value="-1" selected="">---------</option>
                                {% for video in videos %}
                                    <option value="{{ forloop.counter }}">{{ video.navn }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-10">
                            <label for="text${i}">Text</label>
                            <textarea type="text" name="text${i}" class="form-control" id="text${i}" placeholder=""></textarea>
                        </div>
                    </div>
                    <button class="btn btn-danger float-right" id="btn-remove-section${i}" onclick="removeSection(this)" type="button" name="button" >
                        <img src="https://img.icons8.com/material-sharp/24/000000/minus.png">
                        Remove
                    </button>
                </div>
                `
            }


            function addSection() {
                $("#sectionCount").val( +$("#sectionCount").val() + 1)
                var n = $("#sectionCount").val()
                $("form #dynamic-sections").append(create_section_form(n))
            }



            $("#btn-add-section").click(addSection)


            // $("[id^=btn-remove-section]").click(function(e) {
            //     console.log(e)
            //     console.log(2)
            // })

        })
    </script>
{% endblock script %}

courses/templates/courses/course_view.html
{% extends 'songs/base.html' %}
{% block title %}{{ course.title }}{% endblock %}
{% load static %}

{% block head %}

    <script type="text/javascript" src="{% url 'songs:javascript-catalog' %}"></script>

    <style media="screen">
        .course-wrapper {
            color: black;
        }
        .shadow-left-inset {
            -webkit-box-shadow: inset 10px 0px 10px -10px rgba(0,0,0, 0.5);
            -moz-box-shadow: inset 10px 0px 10px -10px rgba(0,0,0, 0.5);
            box-shadow: inset 10px 0px 10px -10px rgba(0,0,0, 0.5);
        }
    </style>
{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'courses:all_courses' %}">Alle kurs</a></li>
    <li class="breadcrumb-item"><a href="{% url 'courses:course_view' course.id  %}">{{ course.title }}</a></li>
{% endblock %}

{% block body %}

    <div class="course-wrapper jumbotron p-4 print-style">

        <div class="row">

            <div class="col">

                {% if course.external %}
                    <h2 class="d-inline">Eksternkurs: {{ course.title }}</h2>
                {% else %}
                    <h2 class="d-inline">Dag {{ course.day }} Bolk {{ course.bulk }}</h2>
                {% endif %}


                <span class="dropdown no-print">

                    <i class="lni-chevron-down cursor-pointer default-theme-link ml-1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>

                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'courses:edit_course' course.id %}"><i class="lni-pencil"></i> Rediger kurs</a>
                        <a class="dropdown-item" href="{% url 'courses:create_playlist' course.id %}"><i class="lni-spotify-original"></i> Lag spotify liste</a>
                        <div class="dropdown-item cursor-pointer" onclick="window.print()"><i class="lni-download"></i> Eksporter (pdf)</div>
                        <a class="dropdown-item" href="{% url 'courses:export_course' course.id %}"><i class="lni-download"></i> Eksporter (docx)</a>
                        <form id="btn-duplicate" class="" onclick="submit()" action="{% url 'courses:duplicate_course' course.id %}" method="post">
                            {% csrf_token %}
                            <div class="dropdown-item cursor-pointer">
                                Dupliser
                            </div>
                        </form>
                    </div>
                </span>

                <hr class="no-print">

                <div class="">
                    {% if not course.external %}
                        <div class=""><b>Tittel</b>: {{ course.title }}</div>
                    {% endif %}
                    <div class=""><b>Instuktør (lead)</b>: {{ course.lead | default:'Ingen valgt' }}</div>
                    <div class=""><b>Instruktør (follow)</b>: {{ course.follow | default:'Ingen valgt'}}</div>
                    <!-- https://ourcodeworld.com/articles/read/555/how-to-format-datetime-objects-in-the-view-and-template-in-django -->
                    <!-- https://docs.djangoproject.com/en/dev/ref/templates/builtins/#date -->
                    <div class=""><b>Dato</b>: {{ course.date | date:'d. M Y (D) ' | default:'TBA' }} (Uke {{ course.date | date:'W' }})</div>
                    <div class=""><b>Når</b>: {{ course.start | date:'H:i' | default:'TBA' }} - {{ course.end | date:'H:i' | default:'TBA' }}</div>
                    <div class=""><b>Hvor</b>: {{ course.place | default:'TBA' }}</div>
                    <div class=""><b>Tags</b>:
                        {% for tag in course.tags.all %}
                            <span class="badge badge-info">{{ tag }}</span>
                        {% endfor %}
                    </div>
                </div>
            </div>

            <div class="col d-none d-lg-block">
                <div class="float-right">
                    <a class="btn btn-dark btn-sm text-light" href="{% url 'courses:edit_course' course.id %}"><i class="lni-pencil"></i> Rediger kurs</a>
                    <a class="btn btn-success btn-sm text-light" href="{% url 'courses:create_playlist' course.id %}"><i class="lni-spotify-original"></i> Lag spotify liste</a>
                    <div class="btn btn-dark btn-sm text-light" onclick="window.print()"><i class="lni-download"></i> Eksporter (pdf)</div>
                </div>
            </div>

        </div>


        <div class="mt-5">
            {% for section in course.sections.all %}
                <div class="mt-4">
                    <h5>{{ section.title }} ({{ section.duration | default:'??' }} min) - {{ section.start | date:'H:i' | default:'hh:mm' }}</h5>

                    {% if section.song %}
                        <div class="font-italic small mb-2">
                            Sang: <a target="_blank" href="{{ section.song.spotify_URL }}">{{ section.song }}</a>
                        </div>
                    {% endif %}

                    {% if section.song2 %}
                        <div class="font-italic small mb-2">
                            Sang: <a target="_blank" href="{{ section.song2.spotify_URL }}">{{ section.song2 }}</a>
                        </div>
                    {% endif %}

                    <div class="pl-4 border-left border-secondary">
                        {{ section.description | safe }}
                    </div>


                    {% if section.video %}
                        <span class="font-italic small no-print">
                            Video: <a target="_blank" href="{{ section.video.youtube_URL }}">{{ section.video }}</a>
                        </span>
                    {% endif %}

                </div>
            {% endfor %}

            {% if course.comments %}
                <div class="text-muted mt-5 font-italic no-print">
                    <hr>
                    <div class="">Kommentarer:</div>
                    <div class="">{{ course.comments | safe | linebreaks }}</div>
                    <hr>
                </div>
            {% endif %}

            <div class="float-right font-italic small no-print">
                Sist redigert av: {{ course.last_editor | default:'Ukjent' }} {{ course.last_edited | date:'(d. M Y - H:i)' }}
            </div>
        </div>

    </div>
{% endblock %}

{% block script %}
    <script type="text/javascript">
        $(document).ready(function() {
            $("footer, #breadcrumb").addClass("no-print");
        })
    </script>
{% endblock script %}